### ISSUE TITLE
do you have the dataset?

### ISSUE THREAD

**Issue by nile649** [ywj95/Example-based-Bokeh-Effect-Challenge#1]
Dataset is supposed to be publicly available but I am no longer able to find it.

**Comment by ywj95** [comment]
the datasets you can see the new github on&nbsp;
https://github.com/YangwjCS/AIM-Workshop-and-Challenge-ICCV-2019


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nilesh Pandey"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月28日(星期二) 凌晨5:08
收件人:&nbsp;"ywj95/Example-based-Bokeh-Effect-Challenge"<Example-based-Bokeh-Effect-Challenge@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ywj95/Example-based-Bokeh-Effect-Challenge] do you have the dataset? (#1)




Closed #1.
